### PR TITLE
MPI snooker update

### PR DESCRIPTION
**Pull request by mdhimes**
Adds snooker walk algorithm to MPI-version. Same as other pull request, but to merge with the DEMC branch rather than MPI branch.

### CODE REVIEW

**Comment by pcubillos** [comment]
Looking good, I'm ready to merge. Just one more question, did you check that the old demc algorithm continues working? (just going over the demo is alright to me).

**Comment by mdhimes** [comment]
I did not explicitly check that; all changes that were made to the code were either adding new inputs (which aren't used by DEMC) or adding snooker-related code wrapped in an if statement (which DEMC wouldn't see). But, I can run that test later today to be sure.

**Comment by pcubillos** [comment]
OK, please do make those checks.  It's important.

**Comment by mdhimes** [comment]
I ran demo01.py and it still works as expected.

**Pull request merged**
